### PR TITLE
Fix url params bug

### PR DESCRIPTION
**Pull request by vtm9**
Better to do it in app, not in the library

### CODE REVIEW

**Comment by mobileoverlord** [comment]
I don't understand the bug you are hitting here. Also, this would remove the join params and the protocol version string.

**Comment by vtm9** [comment]
When I make in my fix:  
   ```
socket_opts = [url: "ws://localhost:4001/ws/websocket?vsn=2.0.0&token=asdf"]
```
returns
```
ws://localhost:4001/ws/websocket?vsn=2.0.0&token=asdf
```
In your case:
 ```
socket_opts = [url: "ws://localhost:4001/ws/websocket", params: %{"token" => "asfd"}]
```
returns
```
ws://localhost:4001/ws/token=asfd
```

**Comment by vtm9** [comment]
@mobileoverlord You haven't got this problems with url generation?

**Comment by mobileoverlord** [comment]
This was fixed in master. I think a blended approach might be best. For example, I don't believe that setting the socket params in the url should be the _only_ way to pass them, but, if a query string were to exist maybe we should merge into it.

**Comment by mobileoverlord** [comment]
I added the functionality to master to merge in from the original URL. Thanks for reporting the issue and for putting forward the effort to get it fixed. I really do appreciate the effort, sorry I didn't merge your PR in this time.

**Comment by mobileoverlord** [comment]
Please give it a go form master and see if it all works for you 😄

**Comment by nallwhy** [comment]
When will you deploy this version?

**Comment by mobileoverlord** [comment]
Oh thanks for the reminder. I’ll put it on my list to push a release.

**Pull request closed without merging**
